сделан news list
xellamay/medical-portal pull request #11
Opened 2023-07-11 09:28 UTC by xellamay

неправильно ветку назвала, надо было назвать news-list

2023-07-13 17:00 UTC, OliverWall requested changes

2023-07-13 17:00 UTC, OliverWall commented on src/hooks/useFetch.ts
> +  const [data, setData] = useState<News[]>([]);
у тебя сечас хук умеет загружать только новости, можем научить его загружать что то еще ?

2023-07-14 09:05 UTC, xellamay commented on src/api/indexApi.ts
> +mock.onGet("/news").reply(200, [...newsFixturesPage]);
не работает если в разные файлы разделять, ответ приходит только на auth запрос

2023-07-14 09:23 UTC, xellamay commented on src/hooks/useFetch.ts
> +  const [data, setData] = useState<News[]>([]);
да да, надо еще докторов научить загружать

2023-07-14 09:24 UTC, xellamay commented on src/components/newsList/NewsList.tsx
> +                id={item.id}
следующая задача будет загрузка новости на отдельной странице, там будет поиск по id этой новости

2023-07-14 09:42 UTC, xellamay commented on src/components/newsCard/NewsCard.module.scss
> +  display: inline-block;
ошибочно, удалила

2023-07-14 09:46 UTC, xellamay commented on src/components/newsCard/NewsCard.tsx
> +  id: string,
для поиска по id новости, для перебора в методе map каждый ребенок должен иметь key, а айди для ключа отличный вариант

2023-07-14 09:47 UTC, xellamay commented on src/pages/homePage/HomePage.tsx
> +    <Slider data={slideFixtures} />
отступы дает компонент Section, он для этого и был создан

2023-07-15 18:40 UTC, OliverWall commented on src/components/newsCard/NewsCard.module.scss
> +  display: inline-block;
еще висит

2023-07-15 18:40 UTC, OliverWall commented on src/components/newsCard/NewsCard.tsx
> +  id: string,
ключи указываются выше а не в комопненте, ты не используешь его сейчас, удали

2023-07-15 18:40 UTC, OliverWall commented on src/components/newsList/NewsList.tsx
> +                id={item.id}
потом и добавишь

2023-07-15 18:40 UTC, OliverWall commented on src/hooks/useFetch.ts
> +  const [data, setData] = useState<News[]>([]);
не только докторов, что угодно

2023-07-18 08:42 UTC, xellamay commented on src/components/newsCard/NewsCard.tsx
> +  id: string,
удалила

2023-07-18 08:42 UTC, xellamay commented on src/components/newsList/NewsList.tsx
> +                id={item.id}
ок

2023-07-18 08:47 UTC, xellamay commented on src/components/newsCard/NewsCard.module.scss
> +  display: inline-block;
теперь точно удалила

2023-07-18 19:07 UTC, OliverWall commented on src/hooks/useFetch.ts
> +  const [data, setData] = useState<News[]>([]);
Если следующей задачей возьмешься делать эту то мердж

2023-07-18 19:07 UTC, OliverWall approved these changes

2023-08-02 19:15 UTC, merged